### ISSUE TITLE
rename to a more generic name?

### ISSUE THREAD

**Issue by tripodsan** [adobe/fetch#302]
in order to make it project helix/franklin independent, maybe consider rename it so a more generic name?

- `@adobe/phetsch`
- `@adobe/phetch`
- `@adobe/fetch-hx`  (http1 + http2)
- `@adobe/w3c-node-fetch`
- ...

or even without `@adobe/`

**Comment by stefan-guggisberg** [comment]
renamed to `@adobe/fetch`
