### ISSUE TITLE
Incorrect exporting of Headers.raw

### ISSUE THREAD

**Issue by hjdhjd** [adobe/fetch#388]
**Description**
The `Headers` class does not currently export the `Headers.raw()` function as it should. This can cause issues in TypeScript when accessing a function that isn't explicitly exported.

**Comment by stefan-guggisberg** [comment]
Thanks for reporting, resolved via #392.

**Comment by hjdhjd** [comment]
Thanks! Is a publish/push to NPM imminent?

**Comment by stefan-guggisberg** [comment]
> Thanks! Is a publish/push to NPM imminent?

probably tomorrow

**Comment by stefan-guggisberg** [comment]
@hjdhjd released: https://github.com/adobe/fetch/releases/tag/v4.0.8
