### ISSUE TITLE
Declare clone() on Response in api.d.ts

### ISSUE THREAD

**Issue by theJC** [adobe/fetch#406]
**Is your feature request related to a problem? Please describe.**
I'm attempting leverage adobe/fetch in a place where the typescript for the framework is expecting the fetch Response type to implement the clone() function.
https://developer.mozilla.org/en-US/docs/Web/API/Response/clone
https://github.com/apollographql/apollo-utils/blob/main/packages/fetcher/src/index.ts#L60

**Describe the solution you'd like**
Add clone() to the Response type.

**Comment by stefan-guggisberg** [comment]
fixed in https://github.com/adobe/fetch/releases/tag/v4.0.11
