### ISSUE TITLE
Feature Request: Bypass alpn LRU cache for non-alpn-negotiated protocols

### ISSUE THREAD

**Issue by theJC** [adobe/fetch#410]
In looking into where adobe/fetch spends its time for my current use case.... I only use h2c, and determineProtocol shows up in profiling much more that I would have expected.

Hypothesis is that it would be more efficient to use the alpn LRU cache only when ALPN protocol is actually negotiated, but if the protocol can be determined by the very simple switch case in the code, then not incur any LRU activity (store/retrieval/stale determination)

Potential alternative, allow one to set the alpn cache size to 0 to disable the alpn cache, similar to how the response cache can be disabled.  I don't believe that option would provide proper flexibility for those who do use combination of protocols.

From analysis of wall time using Datadog profiling showing relative time spent:
<img width="1897" alt="Screenshot 2023-05-16 at 2 07 31 AM" src="https://github.com/adobe/fetch/assets/467023/031457d6-9855-4854-922b-3c2e44e31a99">

**Comment by stefan-guggisberg** [comment]
Good point.

**Comment by stefan-guggisberg** [comment]
released in. v4.0.13
