### ISSUE TITLE
Allow control over socket/session reuse for streams

### ISSUE THREAD

**Issue by kheyse-oqton** [adobe/fetch#417]
Our node service (*A*) is making lots of requests to a service (*B*) over HTTP/2. All requests (appear to) go over a single socket/session, thus not making use of the load balancing on service *B*. Moreover, we hit the limit of max number of concurrent streams over a single socket/session.

Some way to set up multiple sockets/sessions and be able to distribute the requests/streams over these sockets would help solve this problem.

The only option I see is to create multiple `contexts` which also splits/duplicates cache and more.

**Comment by stefan-guggisberg** [comment]
> Our node service (A) is making lots of requests to a service (B) over HTTP/2. All requests (appear to) go over a single socket/session, thus not making use of the load balancing on service B.

That's by design: `adobe/fetch` uses an `Http2Session` per origin and an `Http2Session` uses exactly 1 socket: https://nodejs.org/api/http2.html#http2session-and-sockets

> Moreover, we hit the limit of max number of concurrent streams over a single socket/session.

Have you tried  specifying the `peerMaxConcurrentStreams ` option, e.g. `context({ h2: { peerMaxConcurrentStreams: 200 }})`?
see  https://nodejs.org/api/http2.html#http2connectauthority-options-listener

The other option, as you've already pointed out is using separate contexts. If you don't need caching and you are worried about memory usage you can disable caching.

**Comment by kheyse-oqton** [comment]
> That's by design: adobe/fetch uses an Http2Session per origin and an Http2Session uses exactly 1 socket: https://nodejs.org/api/http2.html#http2session-and-sockets

But in theory adobe/fetch could be edited to use a configurable number of Http2Sessions per origin, or is there any limitation preventing that?

> Have you tried specifying the peerMaxConcurrentStreams option, e.g. context({ h2: { peerMaxConcurrentStreams: 200 }})?
see https://nodejs.org/api/http2.html#http2connectauthority-options-listener

I used env var `DEBUG='adobe/fetch*'` and got this output
```
adobe/fetch:h2 session https://*** remoteSettings: {"headerTableSize":4096,"enablePush":true,"initialWindowSize":65536,"maxFrameSize":16777215,"maxConcurrentStreams":300,"maxHeaderListSize":4294967295,"maxHeaderSize":4294967295,"enableConnectProtocol":false}
adobe/fetch:h2 session https://*** localSettings: {"headerTableSize":4096,"enablePush":true,"initialWindowSize":65535,"maxFrameSize":16384,"maxConcurrentStreams":4294967295,"maxHeaderListSize":4294967295,"maxHeaderSize":4294967295,"enableConnectProtocol":false}
```
so I'm assuming `maxConcurrentStreams` settles to 300, which is still not sufficient.

At this point we just get `NGHTTP2_REFUSED_STREAM` (from the server) when the limit is hit. Wouldn't it make sense for adobe/fetch to handle maxConcurrentStreams more intelligently on the client side, e.g. even with a queue like [grpc](https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0#connection-concurrency) does?

**Comment by stefan-guggisberg** [comment]
> But in theory adobe/fetch could be edited to use a configurable number of Http2Sessions per origin, or is there any limitation preventing that?

> Wouldn't it make sense for adobe/fetch to handle maxConcurrentStreams more intelligently on the client side, e.g. even with a queue like [grpc](https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0#connection-concurrency) does?

it would require complex logic to do some sort of load balancing of the n sessions per origin. That's definitely out of the scope of this module. 

Using different contexts solves your issue.
