### ISSUE TITLE
Backport v4 changes to v3 branch

### ISSUE THREAD

**Issue by theJC** [adobe/fetch#431]
I've leveraged the adobe/fetch library in several of the projects I've worked on.  Unfortunately one of them that would really benefit by having the same improvement that was implemented in https://github.com/adobe/fetch/compare/v4.0.12...v4.0.13 would take significant effort at this point to migrate to ESM and has limited resources available to work on it at this time -- would love to have this available for CommonJS based projects.  Thus I've created a MR with the change for the 3.x branch.

**Describe the solution you'd like**
Backport of these changes into 3.x so the change can be leveraged by CommonJS projects.

MR has been created to accomplish this backport: https://github.com/adobe/fetch/pull/432
- The change to bypass the cache lookup when not necessary since alpn not negotiated
- The correction to the protocol determination

**Describe alternatives you've considered**
Upgrade project to ESM, deemed too much effort and risk at this time.

**Comment by stefan-guggisberg** [comment]
Thanks @theJC . I've merged the PR.
