### ISSUE TITLE
`fetch` hangs with node 20 when using the global agent

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/fetch#467]
Running the following program:
```
import assert from 'assert';
import { h1NoCache } from '@adobe/fetch';

const fetchContext = h1NoCache();
const { fetch } = fetchContext;

const res = await fetch('https://httpbin.org/status/401');
assert.strictEqual(res.status, 401);
```
causes it to hang with node 20,  but **not** with node 18. The program no longer hangs with node 20 as well, as soon as I change the options for the context:
```
4c4
< const fetchContext = h1NoCache();
---
> const fetchContext = h1NoCache({ h1: { keepAlive: false } });
```
The extra `h1` options cause `@adobe/fetch` to use its own agent in https://github.com/adobe/fetch/blob/195959dade3e9ccc646098a4c819113dd2f5b44c/src/core/h1.js#L34-L38

My guess is that the global agent somehow changed its behaviour in node 20.

Note: resetting the fetch context does not change this behaviour.

**Comment by stefan-guggisberg** [comment]
fixed via #469
