### ISSUE TITLE
Inconsistent behaviour when mocking endpoints with msw 

### ISSUE THREAD

**Issue by tompahoward** [adobe/fetch#470]
## Overview
Inconsistent behaviour when mocking endpoints with msw https://mswjs.io/

## Details
When I use msw in my test to mock endpoints, I can get consistent test results, but when I switch to use @adobe/fetch I find that sometimes the mocks are called, and sometimes the real endpoints are called.

## Proposed Actions
No proposed action. Just wondering anyone else has experienced this and if so, how they solved it.

Thanks in advance

**Comment by tompahoward** [comment]
> we use [nock](https://github.com/nock/nock) for all http mocking which works well with @adobe/fetch.
> 
> when you say sometimes the real endpoints are called, is it for some cases or randomly for the same case, or order of
> execution?

It's the same cases that fail randomly. I really can't explain it. One moment, they are all green. Next minute lots of red (I have a lot of negative tests for the servers returning invalid responses or just erroring. They return happy responses when the mocking fails to intercept the calls). Thanks for the nock suggestion. I'm trying that now. I had some initial issues, but so far so good. I just needed to make sure I set up nock a vitest setup file. Maybe I needed to do the same with msw 🤷‍♂️. I'll be trying that next 

> also, how are you using @adobe/fetch ?

We are using it during JWT validation. There are multiple steps to this, and some require HTTP calls.

1. GET https://login.microsoftonline.com/common/.well-known/openid-configuration
2. grab the `jwks_uri` from the response and GET that. It returns an array of key objects
3. Use the `kid` from the JWT header to find a key object with the `kid`.
4. Use the `x5c` property from that key object to validate the signature of the JWT

We need to do JWT validation on every incoming request. Obviously it would be very inefficient to do two outbound https requests for every incoming. Fortunately, both those responses have sensible cache-control values. Switching from native fetch to @adobe/fetch means that most of the time, those requests are served from the cache 👌

**Comment by tompahoward** [comment]
FWIW I just tested with msw in a vitest setup file and it still has issues. I'm sticking with nock. Thank you

**Comment by tompahoward** [comment]
And now nock is doing the same thing 😭

Here's the test FWIW. Putting the nock() into the vitest setup file made no difference in the end.

```
	beforeEach(async => {
		clearCache()
		nockScope = nock(OPEN_ID_CONFIGURATION_HOST)
	})

	afterEach(async => {
		nock.restore()
	})

	describe('getOpenIdConfiguration', async () => {
		test('getOpenIdConfiguration', async () => {
			nockScope.get(OPEN_ID_CONFIGURATION_PATH).reply(...openIdConfigurationResponse)
			expect(
				await getOpenIdConfiguration({
					validator: server.validator,
				}),
			).toHaveProperty('jwks_uri', openIdConfigurationResponse[1].jwks_uri)
		})
	})
```

I'm going to try using vitest's mocking libraries to mock @adobe/fetch directly.

**Comment by tompahoward** [comment]
ok, I ended up combining vitest-fetch-mock and mocking adobeFetch. Here is my setupVitest.ts file

```ts
import createFetchMock from 'vitest-fetch-mock'
import {vi} from 'vitest'
import af, {fetch as adobeFetch, context as adobeContext, clearCache as adobeClearCache} from '@adobe/fetch'

vi.doMock('@adobe/fetch', () => ({
	async fetch(...args: Parameters<typeof adobeFetch>): ReturnType<typeof adobeFetch> {
		// first try to get the response from the cache
		const response = await adobeFetch(args[0], {
			...args[1],
			headers: {...args[1]?.headers, 'Cache-Control': 'only-if-cached'},
		})
		if (response.fromCache) {
			return response
		}

		// otherwise call globalThis.fetch which is mocked by fetchMocker
		return globalThis.fetch(...(args as Parameters<typeof fetch>)) as unknown as ReturnType<typeof adobeFetch>
	},
	clearCache: () => adobeClearCache(),
}))

const fetchMocker = createFetchMock(vi)

fetchMocker.enableMocks()
```

**Comment by tripodsan** [comment]
@tompahoward we had similar issue with mocking the requests to a JWK store. it turned out that we had mixed  versions of `@adobe/fetch` coming from different dependencies. I suggest you do a `npm ls @adobe/fetch` and ensure that all packages are deduped, eg:

```
$ npm ls @adobe/fetch
@adobe/helix-admin@11.37.1 
├─┬ @adobe/fastly-native-promises@3.0.7
│ └── @adobe/fetch@4.1.2 deduped
├── @adobe/fetch@4.1.2
├─┬ @adobe/helix-admin-support@2.7.2
│ └── @adobe/fetch@4.1.2 deduped
├─┬ @adobe/helix-config@2.3.3
│ └── @adobe/fetch@4.1.2 deduped
├─┬ @adobe/helix-deploy@11.0.19
│ ├─┬ @adobe/fastly-native-promises@3.0.6
│ │ └── @adobe/fetch@4.1.1.                      <-------------- here we have a old version, but it doesn't matter because helix-deploy is not loaded during the tests
│ └── @adobe/fetch@4.1.2 deduped
```

**Comment by tompahoward** [comment]
No dups 😔

The previous setupVitest didn't make sense. Here's the latest

```ts
import {type fetch as adobeFetch} from '@adobe/fetch'
import {vi} from 'vitest'
import createFetchMock from 'vitest-fetch-mock'

vi.doMock('@adobe/fetch', () => ({
	async fetch(...args: Parameters<typeof adobeFetch>): ReturnType<typeof adobeFetch> {
		// we could just use this function to return mocked responses,
		// but then we would loose the nice features (like URL matching) of vitest-fetch-mock
		return globalThis.fetch(...(args as Parameters<typeof fetch>)) as unknown as ReturnType<typeof adobeFetch>
	},
}))

const fetchMocker = createFetchMock(vi)

fetchMocker.enableMocks()
```

What are the underlying APIs @adobe/fetch use to make the HTTP requests? I might be able to mock them instead
